### PR TITLE
Filter view by virtual/in-person

### PR DESCRIPTION
**Pull request by warrenyun**
Adds buttons to filter the current events by online, hybrid, or in-person (addresses #155)

preview

### CODE REVIEW

**Comment by warrenyun** [comment]
Update: the first design didn't seem right to me, so I made the design a little more intuitive so that they just click the button to filter/unfilter the events!

Screen Shot 2022-08-17 at 2 18 41 AM

**Comment by maxwofford** [comment]
Hey @NebuDev14, thanks for the PR! I love the feature– def good to have. I'd love to review sometime this week, but if anyone else has the time please go for it!

**Comment by bellesea** [comment]
Hiii @NebuDev14 👋 This feature is awesome hehe — thank you! Your PR reminded me of the filter option at https://toolbox.hackclub.com/home... what do you think about making the design a little more like the one below? so it could have All, Online, and In-person as options in a corner or somewhere...

Screenshot 2022-08-17 at 10 33 18 AM
 
 Would love your thoughts!

**Comment by warrenyun** [comment]
i like the idea! i'll try seeing what i can do

**Comment by bellesea** [comment]
woohoo! please let me know if i can lend a hand :)

**Comment by warrenyun** [comment]
Alright, finished! Let me know what you think :)

filter-preview-2

**Comment by maxwofford** [comment]
This looks super cool! def moving in the right direction. Couple comments on design:

- position of the buttons feels weird– they kinda just float there on the side
- after clicking (`:active`) the button stays scaled up even after mousing away
- the `:hover` and `:focus` colors being the same threw me off– i wasn't sure if i had actually clicked

these are all just minor things– this is getting really close!

**Comment by maxwofford** [comment]
oh, also noticed hybrid events showing up when I filtered for in-person, which i wasn't expecting

**Comment by warrenyun** [comment]
Thanks for the feedback! Thoughts on this?

filter-preview-3

**Comment by bellesea** [comment]
hey warren, that looks awesome! thank you sm for being super quick with making changes hehe :) 

what do you think about adding a bg color + border radius to the group of buttons & removing the border so it looks smth like
Screenshot 2022-08-17 at 5 14 14 PM
Screenshot 2022-08-17 at 5 14 29 PM

(no pressure to have to go with this design, just thinking through ways of further integrating it into the existing design)

**Comment by warrenyun** [comment]
I think that looks cool! I'll implement it!

**Comment by warrenyun** [comment]
Alright! The final design is here:

image

**Comment by maxwofford** [comment]
This is looking great! One last thing– the location pages also show the filter & it feels weird to click "hackathons in LA" and see an online event. Want to just show this on the main page?

**Comment by warrenyun** [comment]
finished! let me know if there's anything else

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/**](https://hackathons-d61ilgz2s.hackclub.dev/) |
|:-:|
|<a href="https://hackathons-d61ilgz2s.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/eFpRRmFDUvhvScmpmUdXp0nhGl0h1L9J_K7hZAxqZ_u699jFOXdz_L3KeoR76nn-mlxMsyxTxA_0mGlegSpSnw.png">(view full size)</a> |







Commit 6f75948c2b6da6cb1a7f584389aec3659e1a6c07 (https://hackathons-d61ilgz2s.hackclub.dev).

**Comment by bellesea** [comment]
@NebuDev14 this is incredible and you're awesome!! Thank you so much for the PR :)

**Comment by warrenyun** [comment]
thanks for the guidance!!

**Pull request merged**
