### PR TITLE
(WIP) Use square event boxes on large screens

### PR DESCRIPTION
**Pull request by maxwofford**
Trying to address this issue https://graphicdesign.stackexchange.com/questions/50928/what-methods-can-i-use-to-create-balance-and-consistency-between-a-group-of-diff/122738

### CODE REVIEW

**Comment by lachlanjc** [comment]
In full support of this, but it’s currently making the logos too big:

This PR:
6730CF2A-B4EB-4050-BF33-F76946492FA3

Current:
2282C989-2334-4618-B61F-A732779E84FB

**Comment by maxwofford** [comment]
Hmmm... yeah. Trying to find the right size for this b/c I kinda want larger logos than the current sizes.

Here's the current PR at 1.25x size for desktops:

Here's at 1x size for desktops (size used in production):

Max Wofford
max@maxwofford.com
Engineering & Operations @ Hack Club ( https://hackclub.com )

**Comment by maxwofford** [comment]
Ah, I should also mention I added space so the logo is in the center of the card b/c the cards on desktop looked top heavy.

Max Wofford
max@maxwofford.com
Engineering & Operations @ Hack Club ( https://hackclub.com )

**Comment by thesephist** [comment]
What's the status here?

**Comment by thesephist** [comment]
@maxwofford is this still WIP?

**Comment by maxwofford** [comment]
I'm looking back at this & kinda in favor of merging. On mobile the logo size is the same as before, but for medium+ screens it's larger in relation to the text. cc @lachlanjc

**Comment by lachlanjc** [comment]
I’m down to keep this going but personally I think it makes the site look broken.

Live site:
2563F5CA-BDD4-4D90-8A61-ACBBC23A2ABC

This PR:
FEFB2FA8-5A8F-42B9-8D6E-1A9347914414

**Comment by lachlanjc** [comment]
Going to close this for now? Feel free to iterate/re-open in the future

**Pull request closed without merging**
