### PR TITLE
Set Chrome autofill text color

### PR DESCRIPTION
**Pull request by exu3**
This PR uses the theme-ui `autofillBackgroundColor` to make the autofill input text readable in dark mode.

Previously:

https://user-images.githubusercontent.com/72365100/140619426-622bb536-e2d5-4cb4-9436-55736af7cc8a.mov

This PR:

https://user-images.githubusercontent.com/72365100/140621559-dca40bdb-4050-47b7-bb58-3ebdc7984280.mov

### CODE REVIEW

**Comment by lachlanjc** [comment]
Styling this is built into Theme UI! https://theme-ui.com/components/input#autocomplete-styles

**Comment by exu3** [comment]
Oh cool TIL. Thanks @lachlanjc!

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/**](https://hackathons-8pyi8orne.hackclub.dev/) |
|:-:|
|<a href="https://hackathons-8pyi8orne.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/Ow1nVt8QcD2UHMAdaPWi0Ku79GMnoxm0cb0tK8ETvn8obpQ_YE1YzyPxitIe62ggASUfRNg_OESamt9ujdVBeA.png">(view full size)</a> |







Commit 5cfc1567a7ee47343ea2441c4bcccaa2da538d1d (https://hackathons-8pyi8orne.hackclub.dev).

**Review by sampoder — APPROVED** [review]
thank u!!!

**Pull request merged**
