### PR TITLE
Reorganise Regional Pages

### PR DESCRIPTION
**Pull request by sampoder**
When I visit a page such as https://hackathons.hackclub.com/list-of-hackathons-in-the-usa, I want to see hackathons but they are buried under loads of other things

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝Changed routes:


| [**/\[region\]**](https://hackathons-cmas3vqzz.hackclub.dev/[region]) |
|:-:|
|<a href="https://hackathons-cmas3vqzz.hackclub.dev/[region]">Screenshot of /[region]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/IKYmsWjKtoDksMe3TfThWBY4nEpWPlbe8dBDprOTmmpVdrEikazfdZPP1v7ynzJsr8g9iOYwd-eZ7vIz5ASQyg.png">(view full size)</a> |







Commit 17636e6afb902b9e3ce586398448b73e1438d196 (https://hackathons-cmas3vqzz.hackclub.dev).

**Comment by zachlatta** [comment]
I like this! But I think we should keep the email thing at the top, since many people will want to see when new emails are added to the list. Maybe we could make it a little less intrusive.

Want to take a stab at that? Then I can merge.

**Comment by sampoder** [comment]
I see, let me take a stab at that @zachlatta!

**Comment by sampoder** [comment]
@zachlatta thoughts on the new changes?

**Comment by zachlatta** [comment]
Hmm, I don't think it's displaying very nicely. What if we kept the full email form at the top?

image

**Comment by sampoder** [comment]
true, but the other one is quite cluttered you know, what if it just said "me@site.com" or whatever and "Get Email Updates"

**Comment by sampoder** [comment]
@zachlatta thoughts :)?

**Comment by sampoder** [comment]
@zachlatta :) hiiiii

**Comment by zachlatta** [comment]
Hey @sampoder, sorry for drawing this out on my end. I'm going to ask @maxwofford to take over for me and work with you to get this merged.

**Comment by maxwofford** [comment]
Hey! Checking out the preview deploy rn.

**Comment by maxwofford** [comment]
@sampoder I like simplifying the email signup, but I think the use-case of the area page is for notification. Here's an example:

- I live in LA so I google "Hackathons in LA"
- The first thing I see is "get notifications for hackathons in LA", but it's "USA" instead of "LA"
Screen Shot 2021-04-05 at 10 51 13
- I either sign up there or scroll & have to go through the locations before seeing the list of hackathons in LA.

---

Maybe we can keep the old form (it's kinda nice that I can explicitly change the location + see how many other people are using it so I know it isn't some random site with 3 users), but drop the locations down to the bottom (like your PR already does)? We'd also need to update the auto-filled location to something more useful for each location page.

Thoughts?

**Comment by sampoder** [comment]
lets do that

**Comment by maxwofford** [comment]
Tag me when ready for final review!

**Comment by sampoder** [comment]
@maxwofford!

**Comment by maxwofford** [comment]
Screen Shot 2021-04-07 at 12 38 38

I went to LA, then clicked Chicago & "LA" was autofilled as location

**Comment by sampoder** [comment]
oh that's weird lemme look into it

**Pull request merged**
