### PR TITLE
Remove groups & pull from Airtable

### PR DESCRIPTION
**Pull request by tmb**

### CODE REVIEW

**Comment by lachlanjc** [comment]
Hi :) This is no small change, & a few things in the code I don’t totally understand. Can you give a thorough breakdown of your changes compared to #2?

**Comment by tmb** [comment]
It is a big change! What I did:

- Updated the `hackathons.hackclub.com` Airtable base to work with the JSON structure already in use in the app
- Removed groups entirely from the fetch & render process. We don't have that in Airtable and don't plan to add it
- Made it fetch records from the Airtable base using api2 (incl. pulling banner + logo directly from Airtable, etc..)

**Comment by lachlanjc** [comment]
Ok cool. Besides finishing removing groups, what of this isn’t covered by #2? Unless I’m missing something that work is already done?

**Comment by lachlanjc** [comment]
Thanks for your work here—I've updated #2 with the new schema. I'm going to go ahead & close this since the other PR has lots of other changes as well. Please comment if we're missing anything! <3

**Comment by thesephist** [comment]
Fyi I think it's courteous to not close another dev's pr without first asking / getting agreement. Closing a marks end of conversation, which is not true on this topic.

I'm fine with continuing the conversation in #2 if everything in this PR is indeed covered there. But I haven't had time to check thoroughly. @tmb can you take point on seeing that that's the case?

**Pull request closed without merging**
