### PR TITLE
haunted house announcement card

### PR DESCRIPTION
**Pull request by ivoinestrachan**

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/**](https://hackathons-i3l63nmdo.hackclub.dev/) |
|:-:|
|<a href="https://hackathons-i3l63nmdo.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/AAE8AGB-Lq0hpSV5D91WdoRrMfg-neluDjrqlbnMDWHYm1EgnYemHybgaTt77RtvucSym_DKlIWm9B3dmX68Yg.png">(view full size)</a> |







Commit 72a24b2a82165e16f21bbfd202dc6f2a04bade62 (https://hackathons-i3l63nmdo.hackclub.dev).

**Review by devramsean0 — APPROVED** [review]
I'm not sure how much I like the placement, (It kinda just feels wrong there)

but LGTM

**Comment by radioblahaj** [comment]
@devramsean0 we kept there b/c all the old ones were there too, like epoch! But what do you recommend?

**Comment by devramsean0** [comment]
not entirely sure, it just feels wrong. but maybe near where the hackathon grant card is?

**Comment by radioblahaj** [comment]
It's also there, so people notice it. We tried a lot of diff placements, but they all looked odd 
image
heres one

**Comment by radioblahaj** [comment]
*here's one we tried out

**Comment by radioblahaj** [comment]
image

**Review by grymmy — APPROVED** [review]
Lgtm at a glance but I did not test, please do so carefully b4 merge

**Pull request merged**
