### PR TITLE
Add `next lint` script

### PR DESCRIPTION
**Pull request by exu3**
This PR adds the `next lint` script and fixes all the eslint warnings/errors.

Screen Shot 2021-11-06 at 11 20 48 AM

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/**](https://hackathons-r4wj1odxl.hackclub.dev/) |
|:-:|
|<a href="https://hackathons-r4wj1odxl.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/8Kj4Zu6e7ihqq99v-eHkcgcMeDEQXWGgiveVD6zmZRVXYK9I2OOiJODCt9Ujiu7VE7KePP-hY_FfgU3ZtdBzkQ.png">(view full size)</a> |







Commit 5e63c17a0c2d640977ad681e5f89e27e6bc5ae7d (https://hackathons-r4wj1odxl.hackclub.dev).

**Review by sampoder — CHANGES_REQUESTED** [review]
Is there a way to make this optional? Last time I used this thing it wouldn't deploy cause I wasn't using next/image and it drove me insane.

**Comment by exu3** [comment]
Yep `ignoreDuringBuilds: true` should ignore it during builds

**Review by sampoder — APPROVED** [review]
sick

**Pull request merged**
