### PR TITLE
APAC hackathons to `/apac` page

### PR DESCRIPTION
**Pull request by exu3**
This PR does the following:
(it's kind of hacky 😳)
-  Adds an /apac page where hackathons based in the APAC region are listed. 
    - This is because APAC hackathons are often not high school student led, are virtual, and are based in a different time zone which caters to a kind type of user who would visit this site
-  Adds a banner on the main page pointing people located in the APAC region to the new page
    - theoretically it's supposed to get the user's IP through the `/api/country` endpoint, then show this banner only if they are in a country in the APAC region, but I didn't get that part working
-  Adds a few redirects to `next.config.js`.
     -  based on feedback from the APAC team, the `list-of-hackthons-in-country` slug is a bit long to type out, so it's now a not-dynamically generated path `/apac` and `list-of-hackathons-in` redirects to `apac`
         - you may have noticed that the region pages are very very outdated, and that's because the Maps API key expired. I'm currently working getting that up and running again and fixing the geocoding Airtable app— it should be done in the next few days
     - (there is a field in the Airtable base for hackathon organizers to indicate whether or not their hackthon is in the APAC region)
     
small thing - it also now uses Airbridge v0.1

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/\[region\]**](https://hackathons-6lhzwby3z.hackclub.dev/[region]) | [**/apac**](https://hackathons-6lhzwby3z.hackclub.dev/apac) |
|:-:|:-:|
|<a href="https://hackathons-6lhzwby3z.hackclub.dev/[region]">Screenshot of /[region]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/xCuild72226gIhIn9ArV_E23gh51dEpG4QdbrIHH37zanShZRYxewAYhqWX8LsxDk7LOmox1DTy3H_mOX4wwpw.png">(view full size)</a> |<a href="https://hackathons-6lhzwby3z.hackclub.dev/apac">Screenshot of /apac</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/4L5sJPm2eNm8_YH6MYoGyrwJSwZiOvwSlh5kz6YutPUX05H5yazxvRrQIkTenJJGewGn4PUaLjZMwS7F5yB7hQ.png">(view full size)</a> |



| [**/**](https://hackathons-6lhzwby3z.hackclub.dev/) |
|:-:|
|<a href="https://hackathons-6lhzwby3z.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/nQGrnYII3v7FwdcLQmmbMIcemgqz27o7J1yug4LGi9DCYYHXLZ19zQzoypUH8wgWl-aVqr0bZA7OKbmA0rOS4g.png">(view full size)</a> |







Commit a5fecf411e434e727dbeb016b34c52274df0b6fe (https://hackathons-6lhzwby3z.hackclub.dev).

**Review by bajpai244 — APPROVED** [review]
Hey Ella, this looks good to me! Great job 🎉

**Review by sampoder — CHANGES_REQUESTED** [review]
Could we please keep the APAC hackathons on the home page? It feels confusing for me as a user for things to have "moved" (now when I click `All Hackathons` I actually get All Hackathons except APAC). Plus we're keeping virtual hackathons on the homepage anyway and we don't claim they're hight school led. 

Could we also make the banner smaller and more integrated? It feels a bit big... I feel like the region section we've got already suffices.

**Comment by exu3** [comment]
Totally hear that, Sam, and thanks for the review. 

The original intention was to have a separate APAC site for listing hackathons in APAC, but the idea was shifted to just having a page on the hackathons.hackclub.com site and the original ideas for a separate site don't really translate well to here since there is already tooling built for regional support here. The reason this was brought up initially was because that people who are not in the APAC region (for example North America) don't typically attend APAC hackathons because of time zones and regional barriers even if it's virtual (this is just based on my observations, and I could totally be wrong here so feel free to correct me if that's the case).

One of the requirements for being listed is being "high school student-led." Although it's not explicitly stated on the form, site, or README, many hackathons have been rejected for being not high school student led (even though high school students can attend the event). A combination of me not being aware of this rule and some exceptions, I've approved non-high school student led hackathons in the past, but was recently asked to remove them. (There is a also a checkbox on the submission form that asks if the organizer is a high school student or not.)

> I feel like the region section we've got already suffices.

Yeah, that totally makes sense, and I agree since this is pretty much exactly what that feature was built for. Also a lot of stuff is dependent on the regions stuff like the events email list. 
Side note: You may notice though, that the regions pages are outdated in part because hackathons have been virtual for over a year now, and the Maps API key is broken because the billing isn't set up (I think that may have to wait until Monday so I can get approval since it deals with money). 

I do also feel that this code is quite janky, and I don't think it should be merged as is. Still thinking about what changes to go forward with though.
Fixing the Maps API key seems like it would probably be a solution to most of the issues. 🤔

I'll cc @MelSmith104 here so she sees this on Monday.

**Comment by sampoder** [comment]
> The original intention was to have a separate APAC site for listing hackathons in APAC, but the idea was shifted to just having a page on the hackathons.hackclub.com site and the original ideas for a separate site don't really translate well to here since there is already tooling built for regional support here. The reason this was brought up initially was because that people who are not in the APAC region (for example North America) don't typically attend APAC hackathons because of time zones and regional barriers even if it's virtual (this is just based on my observations, and I could totally be wrong here so feel free to correct me if that's the case).

That makes sense, but equally you could say as US hackathons transition back to being in person we should therefore create a US-only page as people out of the US are highly unlikely to attend them. I think we're able to achieve the original goal by creating the `/apac` page, we don't need to hide these hackathons on the homepage and only show them to those in APAC, in a way it's a bit unfair to APAC organisers as they get a small audience to tap into and for us makes the site look much less impressive. It's also a confusing UX experience for an APAC user.

> One of the requirements for being listed is being "high school student-led." Although it's not explicitly stated on the form, site, or README, many hackathons have been rejected for being not high school student led (even though high school students can attend the event). A combination of me not being aware of this rule and some exceptions, I've approved non-high school student led hackathons in the past, but was recently asked to remove them. (There is a also a checkbox on the submission form that asks if the organizer is a high school student or not.)

Ahh, thanks for pointing that makes sense. But I don't see how this will fix that? The same application form is being used and the same language is used on the new page, I think the fix to this is more to just change the requirements of the site if we want these hackathons to show up.

**Comment by exu3** [comment]
Yeah I totally get what you're saying about looking at it from a different perspective, and I apologize for my lack of foresight with this PR. I really appreciate your insight and feedback here. I'll implement some changes, get your review, and go over them on Monday with Mel to make sure that this is parallel to what she had in mind for the page.

> Ahh, thanks for pointing that makes sense. But I don't see how this will fix that? The same application form is being used and the same language is used on the new page, I think the fix to this is more to just change the requirements of the site if we want these hackathons to show up.

Right, this PR is unrelated to that; I was just responding to "...we don't claim they're hight school led" (as you noted earlier). I don't think this is an issue right now though cause I don't think people are misunderstanding the language—rather just not reading it entirely or choosing ignoring it :P

**Review by sampoder — APPROVED** [review]

**Comment by sampoder** [comment]
Thanks Ella, thanks for understanding :D

**Pull request merged**
